steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/oceanic-craft-302516/test', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/oceanic-craft-302516/test']
  #images: ['gcr.io/oceanic-craft-302516/test']
#step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'deployment.yml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
#step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment', 
   'app', 
   'app=gcr.io/oceanic-craft-302516/test'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
# push images to Google Container Registry with tags
images: [
   'gcr.io/oceanic-craft-302516/test:latest'
  ]